name: smart_city
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: '>=3.7.0 <4.0.0'

dependencies:
  animated_notch_bottom_bar: ^1.0.3
  cupertino_icons: ^1.0.8
  device_preview: ^1.2.0
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.2.2
  get_it: ^9.0.5
  loading_animation_widget: ^1.3.0
  lottie: ^2.7.0
  shared_preferences: ^2.5.3
  smooth_page_indicator: ^1.2.1

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/animations/

  fonts:
    - family: "Cairo"
      fonts:
        - asset: assets/fonts/Cairo-Regular.ttf
        - asset: assets/fonts/Cairo-Medium.ttf
          weight: 500
        - asset: assets/fonts/Cairo-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Cairo-Bold.ttf
          weight: 700

# flutter_assets:
#   assets_path: assets/images/
#   output_path: lib/core/utils
#   filename: app_images.dart
#   field_prefix: null
